# Reference websites for MOD Launchpad:
# https://maiarlaunchpad.com/
# https://maiar.exchange/

# Site settings

url: "https://MinistryOfDeployment.github.io/"

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Ministry Of Deployment"
title: "Ministry Of Deployment"
description: "MOD Launchpad"
keywords: "Web3.0, Blockchain, IPFS, git, AI, Smart Contract, ..."
favicon: "/img/rocket3.ico"

################
# Header layout #
################

black-favicon: "/img/rocket3.ico"
logo: # leave blank if you don't want a logo

background-img: "../img/output-onlinegiftools.gif"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Nunquam praescriptos transibunt sidera fines."
  - text: "For it is unworthy of distinguished men to waste their time with slavish calculations."
  - text: "What difference do you think you can make, one single man in all this madness? If you die, it's gonna be for nothing."
  - text: "Don't Break the Chain!"

me-img: "/img/farf2.jpeg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: False
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - March 2022"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: ""


# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "This mess is more for me than for you. As "
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/MinistryOfDeployment"
  - title: "instagram"
    url: "https://www.instagram.com/mod.network/"


############
# 404 page #
############

err-404-img: "/img/vitalik.jpg"

##################
# GPG on Keybase #
##################

keybase-username: johnsmith
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
   Chi siamo: 'about'
   Overview: 'latest-post'
   Community: 'contact'
   Roadmap: 'timeline'
   
# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji